appName: EasylearnMobileService
packServiceHost: http://192.168.5.100:8082/
userServiceHost: http://192.168.5.100:8084/

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: DEBUG
  appenders:
    - type: console
    - type: file
      threshold: DEBUG
     # logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: ./log/application.log
      archivedLogFilenamePattern: ./log/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB
metrics:
  reporters:
    - type: graphite
      host: 140.121.101.161
      port: 2003
      prefix: test-easylearn-mobile
